### ISSUE TITLE
Can't Install udm-boot_1.0.1-1_all.deb

### ISSUE THREAD

**Issue by TechFrog467** [michaelpneuman/UDM#1]
Getting, "error processing archive udm-boot_1.0.1-1_all.deb".

root@ubnt:/# dpkg -i udm-boot_1.0.1-1_all.deb
dpkg-deb: error: 'udm-boot_1.0.1-1_all.deb' is not a debian format archive
dpkg: error processing archive udm-boot_1.0.1-1_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 udm-boot_1.0.1-1_all.deb

**Comment by michaelpneuman** [comment]
I will reupload the .deb file.  It may have become corrupted.

**Comment by michaelpneuman** [comment]
I have changed the source for the .deb and removed it from the archive. In the future, I will need to figure out why the file is becoming corrupted.
